/run/verbose 0

# source definition
/gps/particle ion
/gps/ion 95 241
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 32.1 cm
/gps/pos/radius 2.5 mm
/gps/pos/halfz 0.5 mm
/gps/pos/rot1 0 1 0
/gps/pos/rot2 1 0 0
/gps/ang/type iso
/gps/ene/type Mono
/gps/energy 0. keV
/process/had/rdm/nucleusLimits 241 241 95 95

# Set number of particles and start
#/random/resetEngineFrom currentEvent.rndm
/run/beamOn 100
/random/saveThisRun

